# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_form.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_f_main(object):
    def setupUi(self, f_main):
        f_main.setObjectName("f_main")
        f_main.resize(1087, 873)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(f_main.sizePolicy().hasHeightForWidth())
        f_main.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        f_main.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/stripSlice_icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        f_main.setWindowIcon(icon)
        f_main.setAnimated(True)
        f_main.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(f_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(9, 9, 9, 9)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gb_preview = QtWidgets.QGroupBox(self.centralwidget)
        self.gb_preview.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_preview.sizePolicy().hasHeightForWidth())
        self.gb_preview.setSizePolicy(sizePolicy)
        self.gb_preview.setMinimumSize(QtCore.QSize(240, 150))
        self.gb_preview.setMaximumSize(QtCore.QSize(240, 150))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.gb_preview.setFont(font)
        self.gb_preview.setMouseTracking(False)
        self.gb_preview.setTabletTracking(False)
        self.gb_preview.setAcceptDrops(False)
        self.gb_preview.setAutoFillBackground(False)
        self.gb_preview.setObjectName("gb_preview")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.gb_preview)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.vl_preview = QtWidgets.QVBoxLayout()
        self.vl_preview.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.vl_preview.setContentsMargins(2, 2, 2, 2)
        self.vl_preview.setObjectName("vl_preview")
        self.verticalLayout_6.addLayout(self.vl_preview)
        self.verticalLayout.addWidget(self.gb_preview)
        self.l_size_info = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(10)
        self.l_size_info.setFont(font)
        self.l_size_info.setObjectName("l_size_info")
        self.verticalLayout.addWidget(self.l_size_info)
        self.gb_main = QtWidgets.QGroupBox(self.centralwidget)
        self.gb_main.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gb_main.setFont(font)
        self.gb_main.setFlat(False)
        self.gb_main.setCheckable(False)
        self.gb_main.setObjectName("gb_main")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.gb_main)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.b_start = QtWidgets.QPushButton(self.gb_main)
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.b_start.setFont(font)
        self.b_start.setObjectName("b_start")
        self.horizontalLayout.addWidget(self.b_start)
        self.b_stop = QtWidgets.QPushButton(self.gb_main)
        self.b_stop.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.b_stop.setFont(font)
        self.b_stop.setObjectName("b_stop")
        self.horizontalLayout.addWidget(self.b_stop)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.gb_main)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.cb_method = QtWidgets.QComboBox(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.cb_method.setFont(font)
        self.cb_method.setObjectName("cb_method")
        self.cb_method.addItem("")
        self.cb_method.addItem("")
        self.verticalLayout_7.addWidget(self.cb_method)
        self.verticalLayout.addWidget(self.groupBox_5)
        self.gb_file = QtWidgets.QGroupBox(self.centralwidget)
        self.gb_file.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gb_file.setFont(font)
        self.gb_file.setObjectName("gb_file")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.gb_file)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.b_open = QtWidgets.QPushButton(self.gb_file)
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.b_open.setFont(font)
        self.b_open.setObjectName("b_open")
        self.verticalLayout_8.addWidget(self.b_open)
        self.l_filename = QtWidgets.QLabel(self.gb_file)
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.l_filename.setFont(font)
        self.l_filename.setLineWidth(2)
        self.l_filename.setText("")
        self.l_filename.setObjectName("l_filename")
        self.verticalLayout_8.addWidget(self.l_filename)
        self.verticalLayout.addWidget(self.gb_file)
        self.gb_webcam = QtWidgets.QGroupBox(self.centralwidget)
        self.gb_webcam.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gb_webcam.setFont(font)
        self.gb_webcam.setFlat(False)
        self.gb_webcam.setCheckable(False)
        self.gb_webcam.setChecked(False)
        self.gb_webcam.setObjectName("gb_webcam")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.gb_webcam)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.b_cam_connect = QtWidgets.QPushButton(self.gb_webcam)
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.b_cam_connect.setFont(font)
        self.b_cam_connect.setObjectName("b_cam_connect")
        self.verticalLayout_4.addWidget(self.b_cam_connect)
        self.verticalLayout.addWidget(self.gb_webcam)
        self.gb_slice = QtWidgets.QGroupBox(self.centralwidget)
        self.gb_slice.setEnabled(True)
        self.gb_slice.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gb_slice.setFont(font)
        self.gb_slice.setObjectName("gb_slice")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.gb_slice)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.gb_slice)
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.cb_slice_direction = QtWidgets.QComboBox(self.gb_slice)
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.cb_slice_direction.setFont(font)
        self.cb_slice_direction.setObjectName("cb_slice_direction")
        self.cb_slice_direction.addItem("")
        self.cb_slice_direction.addItem("")
        self.horizontalLayout_3.addWidget(self.cb_slice_direction)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.gb_slice)
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.sb_slice_start_position = QtWidgets.QSpinBox(self.gb_slice)
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.sb_slice_start_position.setFont(font)
        self.sb_slice_start_position.setMaximum(0)
        self.sb_slice_start_position.setObjectName("sb_slice_start_position")
        self.horizontalLayout_4.addWidget(self.sb_slice_start_position)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.gb_slice)
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.sb_slice_width = QtWidgets.QSpinBox(self.gb_slice)
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.sb_slice_width.setFont(font)
        self.sb_slice_width.setMinimum(1)
        self.sb_slice_width.setMaximum(1)
        self.sb_slice_width.setObjectName("sb_slice_width")
        self.horizontalLayout_5.addWidget(self.sb_slice_width)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.gb_slice)
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.cb_slice_append_side = QtWidgets.QComboBox(self.gb_slice)
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.cb_slice_append_side.setFont(font)
        self.cb_slice_append_side.setObjectName("cb_slice_append_side")
        self.cb_slice_append_side.addItem("")
        self.cb_slice_append_side.addItem("")
        self.horizontalLayout_6.addWidget(self.cb_slice_append_side)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.verticalLayout.addWidget(self.gb_slice)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setMouseTracking(True)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAutoFillBackground(False)
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setScaledContents(False)
        self.label_5.setWordWrap(False)
        self.label_5.setOpenExternalLinks(True)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.gridLayout.addLayout(self.verticalLayout, 0, 2, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cb_auto_scroll = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(10)
        self.cb_auto_scroll.setFont(font)
        self.cb_auto_scroll.setObjectName("cb_auto_scroll")
        self.horizontalLayout_2.addWidget(self.cb_auto_scroll)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.b_clear = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(10)
        self.b_clear.setFont(font)
        self.b_clear.setObjectName("b_clear")
        self.horizontalLayout_2.addWidget(self.b_clear)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.scroll_image = QtWidgets.QScrollArea(self.centralwidget)
        self.scroll_image.setWidgetResizable(True)
        self.scroll_image.setObjectName("scroll_image")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 817, 785))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scroll_image.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scroll_image)
        self.b_save = QtWidgets.QPushButton(self.centralwidget)
        self.b_save.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(10)
        self.b_save.setFont(font)
        self.b_save.setObjectName("b_save")
        self.verticalLayout_2.addWidget(self.b_save)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        f_main.setCentralWidget(self.centralwidget)

        self.retranslateUi(f_main)
        QtCore.QMetaObject.connectSlotsByName(f_main)

    def retranslateUi(self, f_main):
        _translate = QtCore.QCoreApplication.translate
        f_main.setWindowTitle(_translate("f_main", "Strip Slice"))
        self.gb_preview.setTitle(_translate("f_main", "Preview"))
        self.l_size_info.setText(_translate("f_main", "Size: 0x0"))
        self.gb_main.setTitle(_translate("f_main", "Main"))
        self.b_start.setText(_translate("f_main", "Start"))
        self.b_stop.setText(_translate("f_main", "Stop"))
        self.groupBox_5.setTitle(_translate("f_main", "Method"))
        self.cb_method.setItemText(0, _translate("f_main", "From File"))
        self.cb_method.setItemText(1, _translate("f_main", "From Camera"))
        self.gb_file.setTitle(_translate("f_main", "File"))
        self.b_open.setText(_translate("f_main", "Open File"))
        self.gb_webcam.setTitle(_translate("f_main", "WebCam"))
        self.b_cam_connect.setText(_translate("f_main", "Connect"))
        self.gb_slice.setTitle(_translate("f_main", "Slice"))
        self.label.setText(_translate("f_main", "Direction"))
        self.cb_slice_direction.setItemText(0, _translate("f_main", "Vertical"))
        self.cb_slice_direction.setItemText(1, _translate("f_main", "Horizontal"))
        self.label_2.setText(_translate("f_main", "Position"))
        self.label_3.setText(_translate("f_main", "Width"))
        self.label_4.setText(_translate("f_main", "Append Side"))
        self.cb_slice_append_side.setItemText(0, _translate("f_main", "Standard"))
        self.cb_slice_append_side.setItemText(1, _translate("f_main", "Invert"))
        self.label_5.setText(_translate("f_main", "Created by <a href=\"http://kr3nd31.ru\">KR3ND31</a>"))
        self.cb_auto_scroll.setText(_translate("f_main", "Image Auto Scroll"))
        self.b_clear.setText(_translate("f_main", "Clear Image"))
        self.b_save.setText(_translate("f_main", "Save"))
from GUI import resources
